version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "aperam"
      POSTGRES_PASSWORD: "aperam"
      POSTGRES_DB: "aperam"
    ports:
      - "5433:5432"
    volumes:
      - .docker/db:/var/lib/postgresql/data